export const NOTE_ACTION_TYPE = {
  SET_ALL_NOTES: "note/SET_ALL_NOTES",
  ADD_NOTE: "note/ADD_NOTE",
  REMOVE_NOTE: "note/REMOVE_NOTE",
  FETCH_NOTE_START: "note/FETCH_NOTE_START",
  FETCH_NOTE_SUCCESS: "note/FETCH_NOTE_SUCCESS",
  FETCH_NOTE_FAILED: "note/FETCH_NOTE_FAILED",
  ADD_NOTE_START: "note/ADD_NOTE_START",
  ADD_NOTE_SUCCESS: "note/ADD_NOTE_SUCCESS",
  ADD_NOTE_FAILED: "note/ADD_NOTE_FAILED",
  REMOVE_NOTE_SUCCESS: "note/REMOVE_NOTE_SUCCESS",
  REMOVE_NOTE_FAILED: "note/REMOVE_NOTE_FAILED",
  REMOVE_NOTE_START: "note/REMOVE_NOTE_START",
};
